---
title: "Do MLMs show effects of Embodied Simulation"
author: "Anonymous"
date: "10/10/2019"
output:
  html_document: 
    toc: yes
    toc_float: yes
    theme: flatly
    highlight: kate
    code_folding: hide
    number_sections: yes
    fig_caption: yes
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import files and libraries

```{r}
library(extrafont)
library(tidyverse)
library(stringr)
library(ggtext)
library(xtable)
library(lmerTest)

datasets <- c("connell2007", "pecher2006", "muraki2021")
models <- c("ViT-B-32", "ViT-L-14-336", "ViT-H-14", "imagebind")

fnames <- c()

for (dataset in datasets) {
  for (model in models) {
    fp <- paste0("../results/", dataset, "/", dataset, "_", model,   ".csv")
    fnames <- c(fnames, fp)
  }
}

data <- do.call(rbind,lapply(fnames,read.csv)) %>%
  mutate(
    model = case_match(model,
      "ViT-B-32" ~ "ViT-B/32",
      "ViT-L-14-336" ~ "ViT-L/14",
      "ViT-H-14" ~ "ViT-H/14",
      "imagebind" ~ "ImageBind"
    ),
    model = factor(model, levels=c("ViT-B/32", "ViT-L/14", "ViT-H/14", "ImageBind")),
    dataset = case_match(dataset,
      "connell2007" ~ "Color",
      "pecher2006" ~ "Shape",
      "muraki2021" ~ "Orientation"
    ),
    dataset = factor(dataset, levels=c("Shape", "Color", "Orientation"))
  ) %>%
  mutate(
    item_id = paste(dataset, item, sep="_")
  )

```

# Inferential Statistics

## Aggregate Test

```{r}


# Initialize empty data frame to store summarized results
agg_summary <- data.frame()

# Loop through each unique combination of model and dataset
for (model_name in unique(data$model)) {
  # Subset the data
  subset_data <- data %>%
    filter(model == model_name)
  
  # Run linear model
  result <- summary(lmer(probability ~ match + (1 | item_id) + 
                           (1 | dataset), data = subset_data))
  
  # Store the summarized t-test result in the data frame
  agg_summary <- rbind(agg_summary, data.frame(
    model = model_name,
    estimate = result$coefficients[2,1],
    df = result$coefficients[2,3],
    t_value = result$coefficients[2,4],
    p_value = result$coefficients[2,5]
  ))
}

# View the summarized results
agg_summary <- agg_summary %>%
  mutate(
    model = factor(model, levels=c("ViT-B/32", "ViT-L/14", "ViT-H/14", "ImageBind"))
  )

agg_summary

```


## By Feature type

```{r}

# Initialize empty data frame to store summarized results
lm_summary <- data.frame()

# Loop through each unique combination of model and dataset
for (model_name in unique(data$model)) {
  for (dataset_name in unique(data$dataset)) {
    
    # Subset the data
    subset_data <- data %>%
      filter(model == model_name, dataset == dataset_name)
    
    
    # Run linear model
    result <- summary(lmer(probability ~ match + (1 | item_id),
                           data = subset_data))
    
    # Store the summarized t-test result in the data frame
    lm_summary <- rbind(lm_summary, data.frame(
      model = model_name,
      dataset = dataset_name,
      estimate = result$coefficients[2,1],
      df = result$coefficients[2,3],
      t_value = result$coefficients[2,4],
      p_value = result$coefficients[2,5]
    ))
  }
}

# View the summarized results
lm_summary <- lm_summary %>%
  mutate(
    model = factor(model, levels=c("ViT-B/32", "ViT-L/14", "ViT-H/14", "ImageBind")),
    dataset = factor(dataset, levels=c("Shape", "Color", "Orientation"))
  )

lm_summary


```

```{r}

pivoted_data <- lm_summary %>%

  mutate(
    formatted_p = case_when(
      p_value < 0.001 ~ "\\textbf{<0.001}",
      p_value < 0.05 ~ paste0("\\textbf{", formatC(p_value, format = "f", digits = 3), "}"),
      TRUE ~ formatC(p_value, format = "f", digits = 3)
    ),
    
    dataset = recode(dataset,
      pecher2006="Shape",
      muraki2021="Orientation",
      connell2007="Color"
    )
  ) %>%

  pivot_wider(names_from = dataset, values_from = formatted_p, id_cols = model) %>%
  arrange(model) %>%
  rename(
    Model=model
  ) %>%
  select(Model, Shape, Color, Orientation)

pivoted_data

```


```{r}

latex_table <- xtable(
  pivoted_data,
  caption="p-values from t-tests comparing matching vs mismatching visual features in sentences and images for various models. Values in bold denote significance (p < 0.05). All models except ViT-B/32 show a significant effect for Shape. ViT-H/14 and ImageBind both show significant effects for Color. None of the models show an effect of Orientation.",
  align = c("l", "l", "r", "r", "r")
  )


print(latex_table, 
        type = "latex", 
        hline.after = c(-1, 0, nrow(pivoted_data)), 
        include.rownames = FALSE,
        sanitize.text.function = identity
)

```

# Visualization


```{r}

# Create a custom labelling function
custom_labeller <- function(variable, value) {
  # Replace with your dataset-to-label mapping
  labels <- c(
    pecher2006 = "SHAPE\nPecher (2009)",
    connell2007 = "COLOR\nConnell (2007)",
    muraki2021 = "ORIENTATION\nStanfield & Zwaan (2001)"
    # ... add more mappings if needed
  )
  
  # Extract the attribute (the part before \n) and the reference (the part after \n)
  attribute <- str_extract(labels[value], ".*(?=\n)")
  reference <- str_extract(labels[value], "(?<=\n).*")
  
  # Return the formatted label with attribute in larger font and reference in dark grey
  return(paste0("<span style='font-size:18pt'>", attribute, "</span><br>&nbsp;<span style='font-size:12pt;color:#666666'>", reference, "</span>"))
}

```


```{r}

# Get height of bars
max_bar <- data %>%
  group_by(
    model, dataset, match
  ) %>%
  summarize(
    mean_cl_boot(probability),
    .groups="drop"
  ) %>%
  summarize(
    ymax = max(ymax)
  ) %>% 
  pull(ymax)
  

```

```{r}

# Add a column for significance stars
lm_summary$signif_star <- with(lm_summary, ifelse(p_value < 0.001, '***', 
                                              ifelse(p_value < 0.01, '**', 
                                              ifelse(p_value < 0.05, '*', 'ns'))))

# Merge this significance data with your main dataset
data_with_signif <- merge(data, lm_summary, by = c("model", "dataset"))

lm_summary <- lm_summary %>%
  mutate(
    model = case_match(
      model,
      "ViT-B/32" ~ "B/32",
      "ViT-L/14" ~ "L/14",
      "ViT-H/14" ~ "H/14",
      "ImageBind" ~ "IB"
    ),
    model = factor(model, levels=c("B/32","L/14","H/14","IB")),
    y = case_when(
      p_value < 0.05 ~ max_bar - 0.05,
      T ~ max_bar - 0.03
    )
  )
  

# Plot probability vs match for each model, faceted by dataset
data_with_signif %>%
  mutate(
    model = case_match(
      model,
      "ViT-B/32" ~ "B/32",
      "ViT-L/14" ~ "L/14",
      "ViT-H/14" ~ "H/14",
      "ImageBind" ~ "IB"
    ),
    model = factor(model, levels=c("B/32","L/14","H/14","IB")),
    match = case_match(match,
      "match" ~ "Match",
      "mismatch" ~ "Mismatch"
    )
  ) %>%
  ggplot(aes(x = model, y = probability)) +
  stat_summary(aes(fill = match), fun="mean", geom="bar", position="dodge") +
  stat_summary(aes(fill = match), fun.data="mean_cl_boot", geom="errorbar", position=position_dodge(width=0.9), width=0.2) +
  facet_wrap(~dataset, labeller = labeller(dataset = custom_labeller)) +
  theme_minimal(base_size = 16) +  # Use theme_bw with increased base font size
  scale_fill_manual(values = c("Match" = "#1C73C2CC", "Mismatch" = "#D32F2FCC")) +  # Custom colors
  theme(
    legend.position = "bottom",
    axis.title = element_text(size = 18),  # Increase axis title size
    axis.text = element_text(size = 16),  # Increase axis text size
    axis.text.x = element_text(size = 16),  # Increase axis text size
    strip.text = element_markdown()
  ) +
  geom_text(data=lm_summary, aes(label = signif_star, y = y), vjust = -1, size=6, fontface="plain", color="#222222") +
  coord_cartesian(ylim=c(0, max_bar + 0.05)) +
  labs(x = "Model", y = "Probability", fill = "Match")

ggsave("../manuscript/figures/results.pdf", width = 9, height=5, device="pdf")

```





